# Generated by Django 4.0.2 on 2022-02-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
