# Generated by Django 4.0.2 on 2022-02-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='fund',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loanApp.loan_fund'),
        ),
    ]
