# Generated by Django 4.0.2 on 2022-02-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0005_remove_loan_duration_remove_loan_rate_loan_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanApp.loan_fund'),
        ),
    ]
