# Generated by Django 4.0.2 on 2022-02-28 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0006_alter_loan_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_fund',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
