# Generated by Django 4.0.2 on 2022-02-28 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0007_alter_loan_fund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_fund',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='loan_fund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
