# Generated by Django 4.0.2 on 2022-02-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0008_loan_fund_uuid_alter_loan_fund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_fund',
            name='uuid',
        ),
    ]
