# Generated by Django 4.0.2 on 2022-03-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0006_alter_loan_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='principal',
            field=models.IntegerField(default=2900),
            preserve_default=False,
        ),
    ]
